export const accessoryLabels = {
    basket: "Cesta ou bagageiro",
    lights: "Luzes",
    fenders: "Paralamas",
    bottleHolder: "Suporte para garrafa",
    bell: "Campainha",
    lock: "Cadeado",
    phoneHolder: "Suporte para telefone",
    saddleBag: "Bolsa lateral",
    comfortableSeat: "Assento confortável",
    mirrors: "Espelho retrovisor",
    clipPedals: "Pedais com clip",
    suspension: "Amortecedor",
    rearRack: "Porta-bagagem traseiro",
    chainGuard: "Protetor de corrente",
    onboardComputer: "Computador de bordo",
    helmet: "Capacete",
    gloves: "Luvas",
};